### ISSUE TITLE
[Beacon] Launch Planning

### ISSUE THREAD

**Issue by RobertaJHahn** [IBM/beacon-for-ibm-dotcom#22]
#### Overview
This pilot scope will be to use the Beacon MVP to 1)  run against DDS owned pages to refine the audits and the reports.  2)  engage a select list of adopters to run Beacon against their pages and provide feedback  3)  Plan for the Beacon launch to a broader group of adopters.

This epic will include linked issues to prepare for and launch Beacon to the ibm.com Carbon community.  (3 above)

**Comment by oliviaflory** [comment]
Planning for launch is completed. Launch is TBD
