### ISSUE TITLE
[Beacon] identify specific elements associated with errors whenever possible

### ISSUE THREAD

**Issue by kennylam** [IBM/beacon-for-ibm-dotcom#24]
Audits such as `color-usage-audit` and `text-usage-audit` check for compliance on specific DOM elements, e.g. incorrect color and typography tokens. When an issue is detected the reporting should include the element, for instance using ID, class, or tag names whenever possible.

![image](https://user-images.githubusercontent.com/909118/134519895-a6e525e1-96b0-4280-892e-6c314dd84a8b.png)

**Comment by RobertaJHahn** [comment]
There is no easy engineering solution.  

Decision:  The messaging for the developer should provide instructions of the next steps.  Jan will create the issue.
