### ISSUE TITLE
[Beacon] Run Beacon against selected AEM web pages

### ISSUE THREAD

**Issue by RobertaJHahn** [IBM/beacon-for-ibm-dotcom#41]
#### Overview
As part of the ongoing effort to refine the Beacon rules and provide a high quality tool for the roll-out, Beacon will be run against the AEM pages identified in issue (#40).

#### Additional Information
- list of over 100 AEM pages.  https://airtable.com/shrroTPDunAQm5k9o/tbldAW6npsNXAMHMt
- See Linda's comment below for the specific pages to be used.

#### Acceptance Criteria
- [ ] Beacon is run against all of the AEM web pages included in issue (#40)
- [ ] Results are discussed with Beacon team members
- [ ] Bugs and FR's are created

**Comment by ljcarot** [comment]
From the AEM airtable, I've picked a page built with Learn template and a page built with Solution template in case it reveals via Beacon any differences:   Learn page -> https://www.ibm.com/topics/edi-electronic-data-interchange.  and Solution page -> https://www.ibm.com/blockchain/industries/manufacturing.  cc: @RobertaJHahn
