### ISSUE TITLE
[Beacon] Create the UI and draft icon of the plugin

### ISSUE THREAD

**Issue by RobertaJHahn** [IBM/beacon-for-ibm-dotcom#58]
#### Overview
There is a basic UI included in Lighthouse.  This UI and content could use some refinements / improvements.

1. Key UI here is just 1 button "Generate report" 
2. Additional functions exist in the "settings/options" or the gear on top right
3. Create a draft icon for the bookmarks bar

![image](https://user-images.githubusercontent.com/15144993/141126796-c166f92d-0d8f-4301-88b6-3fe886e3727e.png)

Info from Kenny: 

> so basically i’m think we just simplify the extension popup from the screenshots with a simple ‘audit’ button (or whatever copy) using Carbon components, and maybe some sort of beacon icon?

#### Additional Information
- **See the epic #22 for the overarching descriptions of the work.**
- [Image requirements](https://developer.chrome.com/docs/webstore/images/) from Google extensions

#### Acceptance Criteria
- [ ] Final designs are available and provided to the engineer
- [ ] Content is drafted and included in the web page

**Comment by shixiedesign** [comment]
Info from Kenny: 

![image](https://user-images.githubusercontent.com/15144993/141118478-4e9b056d-6c58-4ab3-8f84-cddaf903b4d2.png)

clicking the ‘options’ cog changes the display to this

![image](https://user-images.githubusercontent.com/15144993/141118503-8f367d0b-64ab-4d35-be3f-863fb471176f.png)

so basically i’m think we just simplify the extension popup from the screenshots with a simple ‘audit’ button (or whatever copy) using Carbon components, and maybe some sort of beacon icon?

**Comment by photodow** [comment]
If all we are is providing them in the popup is a button to click to "audit" the page, then another thing to consider is not using a pop up, and just leverage the browser action to avoid a potential unnecessary additional click.

**Comment by oliviaflory** [comment]
### Icon explorations
Feedback from the design team led me to try out some additional icons using the B and simplifying as much as possible so the icon shines in the extension placement and size.

![Workspace 3-100](https://user-images.githubusercontent.com/45692622/144641793-80c6afdb-9c0f-4857-aed9-8da771f4bc4a.jpg)
![Workspace 4-100](https://user-images.githubusercontent.com/45692622/144641978-3f92bf73-29f2-419a-a6dc-08cdfa54e4b5.jpg)

I selected these three icons to use in the mock ups so we could see a range of icon variations, and also applied the app icon gradients so we could see how those might look in the marketing images required by Google extensions.

![Extension icon options](https://user-images.githubusercontent.com/45692622/144642564-15019f8a-58e8-4c41-bd94-57a6eccf1431.jpg)



### Extension UI
After with @kennylam about what is being audited I used some of the language from the Beacon page on our website to add a bit of a description as to what the extension will do. The Learn more is optional, it could link to the Beacon page on our website so users can review what is being evaluated.

I explored three different widths for the extension:
- Option 1 `256px`
- Option 2`288px`
- Option 3`320px`

![Extension UI options](https://user-images.githubusercontent.com/45692622/144644625-712511b3-7713-4904-9b62-f6d8aa5369b6.jpg)

I'm thinking we could set the extension to change color with the system preferences, so if the user has dark mode set on their system preferences, the extension would change to match.

### Browser mock ups
I have mocked up three of the icons within the browser for us to get an idea of the size and what it might look within the browser. Any of the icons or extension UI options can be swapped out, for this purpose I paired them in order:

#### 1a
![1a](https://user-images.githubusercontent.com/45692622/144644607-24bece79-706e-4cc3-8c4b-3cc5ccfb9caf.jpg)

#### 2b
![2b](https://user-images.githubusercontent.com/45692622/144643747-bae98682-dba7-4082-9ac7-b3a05f227785.jpg)


#### 3c
![3c](https://user-images.githubusercontent.com/45692622/144643766-cd728be0-9ddb-4857-83c0-50212cf6568e.jpg)

**Comment by shixiedesign** [comment]
Well done! Thank you Olivia!
